### ISSUE TITLE
Invalid Package Config when added via yarn and imported

### ISSUE THREAD

**Issue by CodeLuca** [rpldy/react-uploady#100]
Error [ERR_INVALID_PACKAGE_CONFIG]: Invalid package config /Users/lucamarchal/code/ProvePay/node_modules/@rpldy/uploady/package.json. "exports" cannot contain some keys starting with '.' and some not. The exports object must either be an object of package subpath keys or an object of main entry condition name keys only.

**Comment by yoavniran** [comment]
thanks @CodeLuca - #101 should fix this very soon.

**Comment by CodeLuca** [comment]
What can I do to use the library in the mean time?

**Comment by yoavniran** [comment]
install 0.7.1

**Comment by CodeLuca** [comment]
Same issue v0.7.1

`Error [ERR_INVALID_PACKAGE_CONFIG]: Invalid package config /Users/lucamarchal/code/ProvePay/node_modules/@rpldy/shared/package.json. "exports" cannot contain some keys starting with '.' and some not. The exports object must either be an object of package subpath keys or an object of main entry condition name keys only.
    at isConditionalExportsMainSugar (internal/modules/esm/resolve.js:449:13)
    at packageExportsResolve (internal/modules/esm/resolve.js:470:7)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/lucamarchal/code/ProvePay/node_modules/@rpldy/uploady/lib/cjs/Uploady.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_INVALID_PACKAGE_CONFIG'
}`

**Comment by CodeLuca** [comment]
v0.6.0 is last working version fyi.

**Comment by yoavniran** [comment]
exports field was added in 0.7.2 so not sure how thats possible.
try removing node_modules/@rpldy completely and then do: yarn/npm add/i `@rpldy/uploady@0.7.1

**Comment by yoavniran** [comment]
0.7.3 is available now. @CodeLuca Please confirm if issue solved

**Comment by CodeLuca** [comment]
Great response times, thanks man

**Comment by CodeLuca** [comment]
Need to do this for the ui packages as well
upload-preview isn't working still

**Comment by yoavniran** [comment]
thanks @CodeLuca 

- https://github.com/rpldy/react-uploady/blob/master/packages/ui/upload-preview/package.json

- https://unpkg.com/@rpldy/upload-preview/package.json

All packages were updated. its very strange you're still seeing this problem but im guessing it might be some kind of local cache issue

**Comment by CodeLuca** [comment]
Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "lib/cjs/index.js" defined in the package config /Users/lucamarchal/code/ProvePay/node_modules/@rpldy/uploady/package.json; targets must start with "./"

**Comment by CodeLuca** [comment]
Cleared all my yarn cache.

**Comment by yoavniran** [comment]
I see its a little different error now. I will fix. 
Unfortunately Im not seeing this error when i install locally (or in codesandbox)
How are you installing exactly?
what yarn version?
when do you see the error?

**Comment by CodeLuca** [comment]
See the error when just importing uploady into my project anywhere. I'm using node version 14.15.0, yarn version 1.19.1 in a fairly basic project.

**Comment by yoavniran** [comment]
From what little I could find online, seems like its not ready for use until npm@7

So im reverting the use of exports. Will be out in 0.7.4

Im still unclear on "See the error when just importing uploady" - adding an import is not an action that does much until you build/run your project, for example by bundling with webpack. 

I tried adding 0.7.2 or 0.7.3 in a project that uses storybook and I saw:

`WARN unable to find package.json for @rpldy/uploady `

but not the error you described...
