### ISSUE TITLE
Who's Using and How?

### ISSUE THREAD

**Issue by yoavniran** [rpldy/react-uploady#102]
# Using Uploady in Production?

## Or are you planning to?

Please share your use-case and company (if relevant).
It will be great to know how Uploady is used in the wild 🧐

**Comment by dbousamra** [comment]
We are using it in production: 
![image](https://user-images.githubusercontent.com/648137/100722812-bec89380-340c-11eb-851d-7c441457c00e.png)

Have had no major issues.

**Comment by yoavniran** [comment]
That's awesome @dbousamra 
Who's "we"? 🙂

**Comment by oferitz** [comment]
We at [Duality](https://dualitytech.com/) using it. mostly with chunk-uploady to upload very large data files. 
It's an awesome library, thanks for creating it ❤️
