### ISSUE TITLE
Form data ordering

### ISSUE THREAD

**Issue by teejteej** [rpldy/react-uploady#103]
Hi,

Some services like S3 stop reading form data once the 'file' value has been reached.
When looking at the uploady POST request, it starts with the 'file' value, and so the other values like 'key' that are needed for S3, are ignored.

Is there any way in which the order of values for the POST can be changed so that 'file' comes last?

**Comment by yoavniran** [comment]
I'll create a PR that adds the file after the params, so it is read last.
Dont think it should affect anyone else

Technically, you could create a custom sender that does this. ([Drive-Uploady](https://github.com/rpldy/drive-uploady/blob/master/src/getDriveSender.js#L41) uses this capability) It would be pretty simple but its not documented so I'd advise to wait for the next minor version (I'll release shortly)

**Comment by teejteej** [comment]
Excellent thanks!

**Comment by yoavniran** [comment]
@teejteej  0.8.0 is released. Hopefully it solves the issue with S3.

**Comment by teejteej** [comment]
Thanks! Can confirm it fixes S3 uploading.
