### ISSUE TITLE
Adding new files via context.upload(file) doesn't always trigger uploading

### ISSUE THREAD

**Issue by teejteej** [rpldy/react-uploady#105]
When calling context.upload(file), it randomly seems to not trigger the upload process. autoUpload is set to true. 

Trying to force a uploadyContext.processPending() doesn't do anything either.

UPLOADER_EVENTS.BATCH_ADD is successfully called with the correct file though.
Uploadhandler's useRequestPreSend is not called.

Following code is used:
`<Uploady>
  <UploadHandler />
  <UploadButton className="btn btn-primary">
    Upload Files
  </UploadButton>
</Uploady>
`

Any ideas where I could look?

**Comment by yoavniran** [comment]
Its hard to say whats going wrong here. Definitely strange.
Please share a repro sandbox/codepen/etc

**Comment by teejteej** [comment]
I've moved `<Uploady ...>` lower into component hierarchy, and now the issue is resolved.
I'm not sure anymore how to reliably produce an example, so I guess the issue can be closed.

**Comment by yoavniran** [comment]
thanks. interesting issue. if it comes back definitely let me know.
I suspect it may have something to do with re-renders. Uploady should typically be placed very high if not at the top of the tree to avoid needless re-renders. Of course, ensuring memoized props is also important.
