### ISSUE TITLE
Upload button doesn't trigger upload after abort

### ISSUE THREAD

**Issue by oferitz** [rpldy/react-uploady#109]
Here is the reproduce link: https://codesandbox.io/s/rough-lake-5v98z

1. Start a new upload (with large file so you'll have enough time to click the abort).
2. Abort the upload with the abort button.
3. Try to start a new upload.

After choosing a file in the file dialog, the upload process will not start.
As far as I can tell it only happens after abort. If you let the upload process to complete it works fine.

It might be a wrong implementation on my side but I don't think I'm doing anything weird or unusual.

Thanks.

**Comment by yoavniran** [comment]
sandbox is empty... If you can update it so it reproduces, that will be great
I will try and check later myself to see whats the issue

**Comment by oferitz** [comment]
@yoavniran Sorry, I forgot to save...try now

**Comment by yoavniran** [comment]
problem is with abort flow in chunked sender (normal upload abort works fine)
Should have a fix in the next day or two

**Comment by oferitz** [comment]
@yoavniran Great. Thanks for the quick response.
