### ISSUE TITLE
modifying inputFieldName prop does not reflect in formData

### ISSUE THREAD

**Issue by dave-ok** [rpldy/react-uploady#117]
**Describe the bug**
I'm not sure if I am doing this right or if this is a bug, but I have been trying to modify the default `inputFieldName` prop from "file"  to a custom name, say "myCustomField" so that on submission/upload the field name of the file in formData will be "myCustomField". However, even after modifying the `inputFieldName` prop on the `Uploady` component, the field retains the "file" input field name. (P.S I am using a custom component as upload button, even though I think this shouldn't matter)

**To Reproduce**
```
const CustomUploader = ({useMock, fieldName}) => {
  const [isUploading, setIsUploading] = useState(false);
  const [uploadStatus, setUploadStatus] = useState("");

  const onUploading = (value) => setIsUploading(value);
  const handleUploadStatus = (value) => setUploadStatus(value);

  const extraProps={onUploading, handleUploadStatus};

  return (
    <Uploady
      destination={{ url: "http://localhost:5000/v1/mock-path" }}
      autoUpload={false}
      enhancer={useMock ? mockEnhancer : null}
      inputFieldName={fieldName}
    >
      <div className="Uploader">
        <Custombutton { ...{extraProps} }/>
        <UploadProgress animated={isUploading} status={uploadStatus}/>
      </div>
    </Uploady>  
  )
}

const mockEnhancer = (uploader) => {
  const mockSender = createMockSender({ delay: 5000 });
  uploader.update({ send: mockSender.send });
  return uploader;
};

---------------------------------------------------------
Used in another component as:

<CustomUploader fieldName="myCustomField" />
```
Below is a sample formData request on upload

```
XHRPOSThttp://localhost:5000/v1/mock-path
    Content-Disposition: form-data; name="file"; filename="Text.txt"
    Content-Type: text/plain
    Some Text File
```

**Expected behavior**
Expected the request to be as shown below
```
XHRPOSThttp://localhost:5000/v1/mock-path
    Content-Disposition: form-data; name="myCustomField"; filename="Text.txt"
    Content-Type: text/plain
    Some Text File
```

**Versions**
Specify the versions of the @rpldy packages you're using. 
```
    "@rpldy/mock-sender": "^0.8.2",
    "@rpldy/upload-button": "^0.8.2",
    "@rpldy/uploady": "^0.8.2",
```
Which browser this bug reproduces in.
Firefox 81

**Code**
Please provide code sample or better yet, a link to a reproducing repository or best yet, codesandbox (fiddle, etc) where issue can be reproduced easily

**Comment by yoavniran** [comment]
I see you pass `fieldName` to the CustomUploader but not to Uploady, is that the case or just the example here?

On another note,  its inadvisable to put <Uploady> inside a component that re-renders on every state change. I recommend putting it at a higher level of your app

**Comment by dave-ok** [comment]
Thanks @yoavniran. I forgot to include the `inputFieldName` prop here (I did locally). I have updated the sample code to reflect this. The CustomUploader component here is just a helper to keep these components compact. CustomUploader is actually more top-level in the grand scheme of things. Is there something else I am missing concerning the inputFieldName?

**Comment by dave-ok** [comment]
Hi again @yoavniran. Thanks for this amazing library that you built. I am sure you must have spent a lot of time and effort to get it to where it is right now and digging through your own code can be daunting at times.

So, I stumbled across a property, [filesParamName](https://github.com/rpldy/react-uploady/blob/f1990fec4e8c234a7f2d74e4e4868169559911b2/packages/core/shared/src/types.js#L10) in your type definitions for the `destination` prop of the `Uploady` component. I used it and Voila! It worked! I am not sure but it seems this property was not exactly specified in the docs, except for the link to the `Destination` type declaration.

Am I right in assuming this property is doing what the `inputFieldName` prop is supposed to be doing, making it redundant? Please, take a look when you can and thanks again.

**Comment by yoavniran** [comment]
hey @dave-ok great job finding that in the code.
There are two things here:

1) There is a bug. The way you did it in your first example should work. Its an easy fix so I will have it ready today/tomorrow
2) It is also possible to set the param name as part of the `destination` object. The idea is that both can be set, the destination one overrides the UploadOptions one. This way its possible to use different destinations with overriding information on top of the base options.

**Comment by dave-ok** [comment]
Awesome! That makes a lot of sense. I will proceed with my current implementation, and maybe decide to stick with or modify it when the patch is ready. Thanks

**Comment by yoavniran** [comment]
@dave-ok v0.8.3 is out. issue should be fixed.

**Comment by yoavniran** [comment]
thats very strange as I dont see what changed between these versions that could cause this problem. The upload-button packages wasn't changed at all.

I created a [sandbox](https://codesandbox.io/s/react-uploady-asuploadbutton-9ycrc?file=/src/App.js) to test 'asUploadButton' with 0.8.3 and there is no error.

Please share a repro sandbox that I can look into

**Comment by dave-ok** [comment]
I have tried to reproduce in a sandbox but no errors there...strange. https://codesandbox.io/s/hungry-silence-i0vm8?file=/src/App.js
There may be some underlying issues I haven't detected yet, but why they will only surface after an update is what beats me. All I have to do is downgrade, no code change and the problem goes away.

I might just proceed with the previous version till I can make out time to figure out why ... maybe my packages are corrupt?

**Comment by yoavniran** [comment]
it is quite strange as I cant think of any reason why this would happen.
Perhaps try deleting node_modules and reinstalling everything.
Also make sure all Uploady packages in use are upgraded to 0.8.3
