### ISSUE TITLE
Pending and Concurent Upload: Upload of Items is Triggered several Times

### ISSUE THREAD

**Issue by LukasOchmann** [rpldy/react-uploady#122]
**Describe the bug**
When Uplody is created with autoUpload = false and concurrent = true, upload of Items is triggered several Times.

**To Reproduce**
See this Sandbox: https://codesandbox.io/s/vibrant-cdn-b25h6?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js
1. Choose 2 files at once. Click Upload: in the console you can see "batch-1.item-2 Uploading" was logged 2 Times
2. Choose 2 files, one after another. Click Upload: Both "batch-1.item-1" and "batch-2.item2" was logged 2 Times + An Type Error occured.
3. Choose 4 files, two after another two. Click Upload:  "batch-1.item-1" x2; "batch-1.item-2" x 3; "batch-2.item-3" x 6; "batch-2.item-4" x 6

In production i Noticed this behavior in the Network-tab.

**Expected behavior**
Each file only triggered once.

**Versions**
@rpldy/uplody 0.8.3
@rpldy/uploder 0.8.3
@rpldy/sender 0.8.0

Which browser this bug reproduces in.
Tested in Chrome

**Code**
See sandbox above. I wrapped the "send"-method for logging purposes.

**Comment by yoavniran** [comment]
sounds like a bug. I will look into it soon

**Comment by yoavniran** [comment]
This is fixed in the latest version (0.9.0)
You can see in this updated [sandbox](https://codesandbox.io/s/react-uploady-concurrent-with-pending-qqwy3?file=/src/App.js)
I had to fix a couple of minor issues from your sandbox but it looks good now. 
Let me know if youre facing any other issue

**Comment by LukasOchmann** [comment]
Awesome thank you
