### ISSUE TITLE
Need response from upload

### ISSUE THREAD

**Issue by void-m4110c** [rpldy/react-uploady#135]
Hi,

I'm uploading a csv file and some additional parameters to a server.

It's just an upload button to select the file in an uploady component, which is embedded in a table:

  ```javascript
          <TableRow>
              <TableCell>{constructLineDropdown()}</TableCell>
              <TableCell>{constructDatePicker('StartDate')}</TableCell>
              <TableCell>{constructDatePicker('EndDate')}</TableCell>
              <Uploady
                clearPendingOnAdd
                multiple={false}
                accept=".csv"
                params={{
                  lineId: capLineId,
                  startDate: startDate.toISOString().split('T')[0],
                  endDate: endDate.toISOString().split('T')[0],
                }}
                destination={{ url: props.uploadURL }}
              >
                <UploadButton text={i18n.translateToString('UploadFile')} />
              </Uploady>
            </TableRow>
```

I know that the upload works correctly, but is there any way that I can get the HTTPResponse from this upload?

Thanks!

Oh, and don't keep being a dick!

**Comment by yoavniran** [comment]
@void-m4110c Ive replied to you in both times you opened the issue already. Re-creating the issue wont give you more information.
This is your first and last warning about interacting with this repo in a respectful manner. Next time you will be blocked

**Comment by void-m4110c** [comment]
I'm afraid, that's not true. You closed my first request without any answer. Please look it up.

I thought you did the same with my second try. However I see now, that there is a response. 

My mistake. Sorry for that

**Comment by yoavniran** [comment]
look closely at the thread on the first issue:

<img width="1334" alt="Screen Shot 2021-02-19 at 10 40 28" src="https://user-images.githubusercontent.com/1102278/108479966-0ab60680-729f-11eb-9029-f6c36f24f3d2.png">

The issue was transferred to a discussion, thats why it was closed
If you have more questions you can add them there

**Comment by void-m4110c** [comment]
Aah I see now. This is new... Ok, sry and thx again.
