### ISSUE TITLE
Is there a way to manipulate the HTTP headers before uploading a file?

### ISSUE THREAD

**Issue by plamber** [rpldy/react-uploady#140]
**Is your feature request related to a problem? Please describe.**
I was looking for a way to manipulate the header information before uploading a file. We have an API that requires a Baerer token for authentication. Before triggering the upload process I would need to retrieve the baerer token and update the header information before posting the file.

Unfortunately, I haven't found an example how you can do this.

Thank you very much for your feedback

**Comment by yoavniran** [comment]
moving to [discussions](https://github.com/rpldy/react-uploady/discussions). will answer there
