### ISSUE TITLE
Completed shows wrong value after reupload using retryEnhancer

### ISSUE THREAD

**Issue by aleksander-lurie** [rpldy/react-uploady#147]
**Describe the bug**
Using tus-uploader with retryEnhancer it's correctly continue upload a chunks after eg. refreshing page.
item.completed property from `useItemProgressListener` event start counting from the beginning, also `item.loaded` property looks the same.

**Expected behavior**
Uploader should provide a correct values including previously successfully uploaded chunks

**Versions**
```
    "@rpldy/retry": "^0.10.0",
    "@rpldy/retry-hooks": "^0.10.0",
    "@rpldy/shared": "^0.10.0",
    "@rpldy/tus-uploady": "^0.9.0",
    "@rpldy/upload-button": "^0.9.0",
    "@rpldy/upload-drop-zone": "^0.9.0",
    "@rpldy/uploader": "^0.9.0",
    "@rpldy/uploady": "^0.9.0",
```

**Code**
`UploadyContextComponent.js`

```
//other import above
import TusUploady  from "@rpldy/tus-uploady";
import { retryEnhancer } from "@rpldy/retry";
//other imports below

//some other code inside component
<TusUploady
    destination={{
      url: `${process.env.REACT_APP_API_URL}/upload-resumable`,
      headers: { Authorization: `Bearer ${token}` },
    }}
    enhancer={retryEnhancer}
    concurrent={evalBool(process.env.REACT_APP_UPLOAD_CONCURRENT)}
    maxConcurrent={evalInt(process.env.REACT_APP_UPLOAD_MAX_CONCURRENT)}
    chunkSize={evalInt(process.env.REACT_APP_UPLOAD_CHUNK_SIZE)}
    autoUpload={evalBool(process.env.REACT_APP_UPLOAD_AUTO)}
    sendDataOnCreate={evalBool(process.env.REACT_APP_UPLOAD_SEND_DATA_ON_CREATE)}
    withCredentials={evalBool(process.env.REACT_APP_UPLOAD_WITH_CREDENTIALS)}
  >
//som other code
```

`UploadProgress.js`

```
import { FILE_STATES } from "@rpldy/shared";

import PublishIcon from '@material-ui/icons/Publish';
import HourglassEmptyIcon from '@material-ui/icons/HourglassEmpty';
import DoneIcon from '@material-ui/icons/Done';
import PriorityHighIcon from '@material-ui/icons/PriorityHigh';
import BlockIcon from '@material-ui/icons/Block';
import HelpOutlineIcon from '@material-ui/icons/HelpOutline';

import CircularProgress from "components/CircularProgress";

function UploaderProgress({item}) {

  const { completed, state } = item;

  return(<CircularProgress value={completed} title={state}>
    {state === FILE_STATES.FINISHED && <DoneIcon />}
    {state === FILE_STATES.UPLOADING && <PublishIcon />}
    {state === FILE_STATES.PENDING && <HourglassEmptyIcon />}
    {state === FILE_STATES.ADDED && <HourglassEmptyIcon />}
    {state === FILE_STATES.ERROR && <PriorityHighIcon />}
    {state !== FILE_STATES.ERROR && (state === FILE_STATES.CANCELLED || state === FILE_STATES.ABORTED) && <BlockIcon />}
    {!Object.values(FILE_STATES).some(fileState => fileState === state) && <HelpOutlineIcon />}
  </CircularProgress>)
}

export default UploaderProgress;
```

**Comment by yoavniran** [comment]
thanks @aleksander-lurie 
sounds like a bug. I will investigate

**Comment by aleksander-lurie** [comment]
This issue still persists after upgrade all packages to latest versions

**Comment by yoavniran** [comment]
@aleksander-lurie 0.11.2 is out with a fix
Please let me know if youre still having issues after upgrading

**Comment by aleksander-lurie** [comment]
I cant use the latest version of packages (0.11.2) after upgrade i got: `ReferenceError: BUILD_TIME_VERSION is not defined`

`node_modules/@rpldy/shared-ui/lib/esm/uploadyVersion.js:5`
```2 | 
  3 | /* istanbul ignore next */
  4 | // eslint-disable-next-line no-undef
> 5 | var VERSION = BUILD_TIME_VERSION || "";
  6 | export var GLOBAL_VERSION_SYM = Symbol["for"]("_rpldy-version_");
  7 | 
  8 | var getVersion = function () {```

**Comment by yoavniran** [comment]
There's a build issue with 0.11.2 (will deprecate it) 
I will fix and publish a new version and let you know
thanks for trying

**Comment by yoavniran** [comment]
0.11.3 is out. Please try

**Comment by aleksander-lurie** [comment]
Well done! Now it works perfectly 🤌  Thank you a lot 🙏  😃

**Comment by aleksander-lurie** [comment]
Hi again @yoavniran 
Unfortunately still something is wrong. At this moment uploady correctly re-initialize current status of the partially uploaded file but.... looks like you forgot sum up or took wrong filesize (only remained part we have to upload, without already uploaded chunks) to calculate how much still have to be uploaded. So at the and progress shows 100% too early.

Example:

File size to upload: 100MB, aborted after 40MB so 60MB still have to be retried. After retrying uploay correctly set up progres to 40% but laso it took only 60MB filsesize to calculate that progress. So i got progress 100% while i still have 20MB to upload :)

BTW: cheers from Codete ;)

**Comment by yoavniran** [comment]
strange. Can you log to console from the useItemProgressListener callback and write out the `loaded`, `completed` and `file.size` prop?
Please share it here so i can take a look. Im not sure what is missing from the calculation yet

**Comment by yoavniran** [comment]
> BTW: cheers from Codete ;)

Cheers! 😄

**Comment by yoavniran** [comment]
closing due to no info. Will reopen when more details are available
