### ISSUE TITLE
Uncaught Invariant Violation: Uploady - valid UploadyContext not found

### ISSUE THREAD

**Issue by cristianbuta** [rpldy/react-uploady#151]
Describe the bug
Using the Upload Drop Zone implementation from the provided example throws the following error in console: Uncaught Invariant Violation: Uploady - valid UploadyContext not found. Make sure you render inside <Uploady>

To Reproduce

Set up a react project with typescript/webpack
Add the https://react-uploady-storybook.netlify.app/?path=/docs/upload-drop-zone--with-drop-handler
Visit the app in the browser
See error
Expected behavior
There should be no error.

Versions
"@rpldy/upload-drop-zone": "^0.11.0",
"@rpldy/uploady": "^0.10.0",
Ubuntu 18
Google Chrome

Code
![image](https://user-images.githubusercontent.com/41893422/110027666-f102cd80-7d3a-11eb-82cf-9bf36eeb640c.png)
```

import React from 'react';
import Uploady from '@rpldy/uploady';
import UploadDropZone from '@rpldy/upload-drop-zone';

const App = () => (
  <Uploady
    autoUpload={false}
  >
    <UploadDropZone
      onDragOverClassName='drag-over'
      grouped={false}
      maxGroupSize={1}
    >
      <span>Drag&Drop File(s) Here</span>
    </UploadDropZone>
  </Uploady>
);

export default App;
```

**Comment by yoavniran** [comment]
@cristianbuta make sure your Uploady packages are of the same versions
currently you have a mix of 0.10 and 0.11 which is causing this issue
In the near future I plan  to  add a warning about this mismatch

**Comment by Goowwy** [comment]
i have same issue 
Uncaught Invariant Violation: Uploady - Valid UploadyContext not found. Make sure you render inside <Uploady>

version is the same 
"@rpldy/upload-button": "^1.1.0",
    "@rpldy/upload-drop-zone": "^1.1.0",
    "@rpldy/upload-preview": "^1.1.0",
    "@rpldy/uploady": "^1.1.0",

**Comment by yoavniran** [comment]
@Goowwy I recommend deleting node_modules and reinstalling. There shouldnt be a problem when all packages are synced.
let me know if this helps or not

**Comment by moosemoose22** [comment]
Thanks for the awesome library. Just wanted to say that I'm getting the same error right now, and I'm using version 1.4.0 of @rpldy/upload-button and @rpldy/uploady. I've deleted node_modules and reinstalled it a few times.

**Comment by yoavniran** [comment]
thanks @moosemoose22 
Please open a new issue in case this is reproducing.
