### ISSUE TITLE
Promise support on types for `useRequestPreSend`

### ISSUE THREAD

**Issue by larrifax** [rpldy/react-uploady#158]
**Describe the bug**
The [dynamic parameters guide](https://github.com/rpldy/react-uploady/blob/master/guides/DynamicParameters.md) states that:

> The handler may return the response immediately or as a promise which resolves to the response

This is not reflected in the Typescript types for `useRequestPreSend` defined [here](https://github.com/rpldy/react-uploady/blob/6bd768aa1137950d880884811dc6934bf5ba8a98/packages/ui/shared/types/index.d.ts#L81)

**To Reproduce**
1. Attempt to use an async function in `useRequestPreSend`
2. Observe Typescript error stating that the async function is not assignable to the parameter for `useRequestPreSend`

**Expected behavior**
No Typescript errors, as async functions are allowed.

**Versions**
`0.11.3` (and earlier)

**Code**
The following Typescript type definition could work:
```
type UseRequestPreSendResponse = { items?: BatchItem[]; options?: CreateOptions }

export const useRequestPreSend: (cb: (data: PreSendData) => UseRequestPreSendResponse | Promise<UseRequestPreSendResponse>) => void;
```

**Comment by larrifax** [comment]
Thanks! 🎉

**Comment by yoavniran** [comment]
thanks @larrifax -  0.11.4 is now published with the fix
