### ISSUE TITLE
Typescript error inside @rpldy/uploady/types/index.d.ts

### ISSUE THREAD

**Issue by gsteenkamp89** [rpldy/react-uploady#163]
**Describe the bug**
There is a Typescript error in @rpldy/uploady/types/index.d.ts(3,13).
A `type` called `InputRef ` is being imported to `@rpldy/uploady/types/index.d.ts` from `@rpldy/shared-ui`
The type `InputRef` is already declared a type upon export inside `@rpldy/shared-ui`, but is being *redeclared* as a type upon import inside `@rpldy/uploady/types/index.d.ts`, causing a Typescript error.

**To Reproduce**
1. install these packages  into create React App project (using **Typescript**): (*package.json below*)
  > "@rpldy/upload-button": "^0.11.4",
  >  "@rpldy/upload-preview": "^0.11.4",
  > "@rpldy/uploady": "^0.11.4",
  > "typescript": "~3.7.2",

2.  run `yarn install` to install these packages
3.  run `yarn start` to start dev server
4.  Get typescript error `TypeScript error in ~app/node_modules/@rpldy/uploady/types/index.d.ts(3,13):
'=' expected.  TS1005`(see screenshot below)

![Screenshot 2021-04-21 at 12 51 03](https://user-images.githubusercontent.com/51655063/115542701-d65fc600-a2a0-11eb-8eef-2f341157178f.png)

**Expected behavior**
I expect this to compile and run as needed

**Versions**
 > "@rpldy/upload-button": "^0.11.4",
 >  "@rpldy/upload-preview": "^0.11.4",
 > "@rpldy/uploady": "^0.11.4",

**Code**
all code is inside this repo

**Comment by yoavniran** [comment]
hey @gsteenkamp89 
As far as i can tell (and Im not a TS expert), there is no issue with the way the type is imported. 
I run TS compile as part of Uploady's build process and it doesnt complain. 
I just created a new CRA with TS and installed the Uploady dependencies. I then ran `yarn start` and it succeeded with no errors.

It installed TS 4+ but even if I downgrade to TS 3.7.2 as you mentioned, Im still able to yarn start without a problem.

Can you share a repo where this is happening? So I can see the issue for myself

**Comment by gsteenkamp89** [comment]
That's really strange. Unfortunately this is happening inside a client repo so I can not share it just yet. I will try to duplicate this issue in a separate repo and post it here. :)

**Comment by gsteenkamp89** [comment]
Okay this turned out to be a Typescript compiler issue. I changed Typescript version and since I'm using Yarn I also added *resolutions* field to package,json and that fixed the issue.
Thanks for the help!
```
"dependencies": {
...
"@rpldy/upload-button": "^0.11.4",
    "@rpldy/upload-preview": "^0.11.4",
    "@rpldy/uploady": "^0.11.4",
    "typescript": "^4.1.1",
  },
  "resolutions": {
    "**/@typescript-eslint/eslint-plugin": "^4.1.1",
    "**/@typescript-eslint/parser": "^4.1.1"
  },
```
