### ISSUE TITLE
Type error on useRequestPreSend when returning false

### ISSUE THREAD

**Issue by zgottlieb** [rpldy/react-uploady#164]
**Describe the bug**
The documentation for `useRequestPreSend` states that this hook is cancellable, meaning that the hook's callback function should be able to return `false` in order to cancel the upload. This works when implemented, however Typescript complains about the return type of the callback function when `false` is returned.

This error makes sense given that the return type for this callback function is defined as `PreSendResponse | Promise<PreSendResponse>`, however given the nature of cancellable events, it seems that `boolean` or `false` should also be a valid return type.

**To Reproduce**
1. Implement `useRequestPreSend` hook in Typescript app
2. Return `false` from the callback function
3. Run Typescript compiler

**Expected behavior**
Typescript should not complain about returning `false` in the `useRequestPreSend` hook (similar to the use of other cancellable event hooks, such as `useItemStartListener`).

**Versions**
0.11.4

**Code**
I can provide a code sample if necessary, but I figure this one is pretty straightforward.

**Comment by yoavniran** [comment]
hey @zgottlieb , good catch. I'll create a fix shortly and publish soon. thanks

**Comment by yoavniran** [comment]
@zgottlieb 0.11.5 is out with a fix. Please confirm it solves your issue

**Comment by zgottlieb** [comment]
Thank you for jumping on this so quickly!

I installed 0.11.5 and I see that the typings are updated, however for my specific use case I still get a TypeError. My use case of `useRequestPreSend` returns a promise that conditionally returns either a PreSendResponse or `false`, so I suppose `Promise<PreSendResponse | boolean>` would also have to be added to these typings.

**Comment by yoavniran** [comment]
just the thing that makes me hate TS... 😞
Will add the fix shortly

**Comment by yoavniran** [comment]
@zgottlieb plz check 0.11.6.

**Comment by zgottlieb** [comment]
Works! Thanks again @yoavniran!
