### ISSUE TITLE
Allow selecting both directories and files for upload

### ISSUE THREAD

**Issue by mart-jansink** [rpldy/react-uploady#168]
**Is your feature request related to a problem? Please describe.**
My users need to be able to select both directories and files for uploads. This sadly can't be done with in one go because setting the `webkitdirectory` attribute disables the selection of single files (at least in Chrome on macOS). The best approach I found is providing the user with two buttons: a "upload files" and "upload directory" one. Then call `.showFileUpload()` from their click handler after setting the `webkitdirectory` attribute to respectively `false` or `true` on the file input. However, this is slightly complicated because there's no reference to this input available.

**Describe the solution you'd like**
Make the `fileInputRef` available in the `UploadyContext`.

**Describe alternatives you've considered**
Have `.showFileUpload()` apply the `webkitdirectory` option (and also e.g. the `multiple` one) before calling `input.click()`. Or even add a `.showDirectoryUpload()` method that does the same.

**Comment by yoavniran** [comment]
Hi @mart-jansink 
This should be possible using the custom input setup. It was mostly documented under the [useFileInput](https://github.com/rpldy/react-uploady/tree/master/packages/ui/uploady#useFileInput) hook info.

To help make it clearer, I just published a new guide: [Custom Input](https://github.com/rpldy/react-uploady/blob/master/guides/CustomInput.md)
Specifically the [custom button](https://github.com/rpldy/react-uploady/blob/master/guides/CustomInput.md#with-custom-button) code example there should help you. 

Let me know if this answers your need or if you still need assistance.

**Comment by tacohiddink** [comment]
Hi @mart-jansink 
Why not use the Drag & Drop component (this enables dragging of files and complete folders) and combine that with a button (to select files only)

**Comment by mart-jansink** [comment]
@tacohiddink Sadly drag&drop doesn't provide the files in nested directories, nor does it give it a `webkitRelativePath` that you do get using the `webkitdirectory` attribute on the file input. And for some of the content that my users can upload the directory structure is quite important to retain. At the same time, these directories can be really big (100GB+) so zipping them isn't always an option since these files are nearly incompressible anyway.

@yoavniran Thanks, that's exactly what I'm doing now. But I thought it'd be easier to be able to use a reference to the file input that's already being created and hoped that other people could benefit from this.

**Comment by tacohiddink** [comment]
@mart-jansink maybe I am missing something, but I am able to drag and drop complete nested directories onto the d&d component.
Did have to provide these settings:

`htmlDirContentParams={{ recursive: true, withFullPath: true}}`

**Comment by yoavniran** [comment]
@mart-jansink im conflicted over exposing a ref to the internal input. 
Im not sure if in the long run it will be good to have that part of the public API.
That is why I allowed handing a custom input from the outside for advanced use-cases that are a small fraction of what users typically require.
I'll keep this in mind and think about whether its something to add in the future.

For now Ill move this issue to the discussions section for others to see.
