### ISSUE TITLE
WebKitFormBoundary's are being added to all S3 uploads

### ISSUE THREAD

**Issue by pbaker0804** [rpldy/react-uploady#190]
I apologize if this has already been asked or if it's a non-issue, but I'm trying to use this tool to upload into AWS S3 and WebKitFormBoundary's are being added to all file content-types that I upload.  

Here's an example:
```
------WebKitFormBoundaryQATKZg64RAGAISRM
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

This is text.
------WebKitFormBoundaryQATKZg64RAGAISRM--
```

I'm following this article as a prototype that has react-uploady under the hood: https://dev.to/danstanhope/react-file-upload-using-s3-pre-signed-urls-1a6d

Here is a function that I'm executing.  Do I need to add something in options?

```
const SignedUploadDragAndDrop = () => {
  useRequestPreSend(async ({ items, options }) => {
    const files = items.length > 0 ? items[0] : {};

    let { file } = files;
    let { name, type } = file;
    let organizationId = 526;
    let gateway = `http://secret`;

    let url = `${gateway}?` + new URLSearchParams({name,type});
    let config = {
      headers: {
        'X-Core-Authorization': 'secret'
      }
    }

    const response = await axios(url, config);
    let { data } = response;
    let uploadUrl = data.data[0];

    return {
      options: {
        destination: {
          url: uploadUrl,
          method: 'PUT',
          headers: {
            'Content-Type': type
          }
        },
      },
    };
  });
```

Thank you so much for any help!

**Comment by yoavniran** [comment]
Hi @pbaker0804 
These are added since by default Uploady uses [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) to upload files. Therefore, using `multipart/form-data`

This typically how servers are set up to receive files.

In case you want Uploady to avoid using FormData, you can set the prop: `sendWithFormData` to _false_

This will send the file as the body of the upload request.

Hope this helps.

**Comment by pbaker0804** [comment]
> Hi @pbaker0804
> These are added since by default Uploady uses [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) to upload files. Therefore, using `multipart/form-data`
> 
> This typically how servers are set up to receive files.
> 
> In case you want Uploady to avoid using FormData, you can set the prop: `sendWithFormData` to _false_
> 
> This will send the file as the body of the upload request.
> 
> Hope this helps.

That was it!  Thanks for the quick reply...

    ```
return {
      options: {
        **sendWithFormData: false,**
        destination: {
          url: uploadUrl,
          method: 'PUT',
          headers: {
            'Content-Type': type
          },
        },
      },
```
