### ISSUE TITLE
Chunk Upload Progress Event Issues!

### ISSUE THREAD

**Issue by vinodkhandelwal** [rpldy/react-uploady#203]
I am trying to upload 2 files with chunk feature and using different events to use the progress event. But i see some discrepancy in the progress detail. Please see below the log message that i am getting. 
```
Total size to upload:21218992
index.tsx:203 CHUNK_EVENTS.CHUNK_START -> 1 Chunk Start of 1
index.tsx:189 UPLOADER_EVENTS.ITEM_PROGRESS -> T_Prop_Bicycle_BC.jpg upload Progress: 100% 
index.tsx:215 CHUNK_EVENTS.CHUNK_FINISH -> item.loaded 248223
index.tsx:203 CHUNK_EVENTS.CHUNK_START -> 1 Chunk Start of 3
index.tsx:189 UPLOADER_EVENTS.ITEM_PROGRESS -> test20mb2.fbx upload Progress: 40.00359058380127% 
index.tsx:215 CHUNK_EVENTS.CHUNK_FINISH -> item.loaded 8389361
index.tsx:203 CHUNK_EVENTS.CHUNK_START -> 2 Chunk Start of 3
index.tsx:189 UPLOADER_EVENTS.ITEM_PROGRESS -> test20mb2.fbx upload Progress: 100% 
index.tsx:215 CHUNK_EVENTS.CHUNK_FINISH -> item.loaded 25167330
index.tsx:203 CHUNK_EVENTS.CHUNK_START -> 3 Chunk Start of 3
index.tsx:189 UPLOADER_EVENTS.ITEM_PROGRESS -> test20mb2.fbx upload Progress: 100% 
index.tsx:215 CHUNK_EVENTS.CHUNK_FINISH -> item.loaded 37750995  
```
Here are the issue that i am seeing - 
 - Getting upload progress as 100% early even when all chunks are not upload. 
 - Item.loaded value is way higher than total file size upload. In my example i am uploading total 21218992 only. 
I am using event handlers as below  - 

```
uploader.on(UPLOADER_EVENTS.ITEM_PROGRESS, (item) => {
      console.log(`UPLOADER_EVENTS.ITEM_PROGRESS -> ${item.file.name} upload Progress: ${item.completed}% `);      
    });
uploader.on(CHUNK_EVENTS.CHUNK_START, ({ chunk, totalCount }) => {
      console.log(`CHUNK_EVENTS.CHUNK_START -> ${chunk.index + 1} Chunk Start of ${totalCount}`);     
    });

    uploader.on(CHUNK_EVENTS.CHUNK_FINISH, ({item}) => {
      console.log(`CHUNK_EVENTS.CHUNK_FINISH -> item.loaded ${item.loaded}`);     
    });
```
Am I using these event in a wrong way? Please help.

**Comment by yoavniran** [comment]
@vinodkhandelwal please share how you are initializing the uploader instance
preferably with a reproducing codesandbox/codepen or with a GH repo

**Comment by yoavniran** [comment]
also, does the issue occur when you're uploading just one file or only with multiple?

**Comment by yoavniran** [comment]
thanks @vinodkhandelwal 
im currently on vacation so ill have a look at this when I get back in a few days

**Comment by yoavniran** [comment]
@vinodkhandelwal 0.13.3 is now out. 
Should solve your issue. Please report if there are still issues
