### ISSUE TITLE
UPLOADER_EVENTS.REQUEST_PRE_SEND: items array has undefined value

### ISSUE THREAD

**Issue by creage** [rpldy/react-uploady#232]
**Describe the bug**
After upgrading to the 0.13.3 the `items` argument for `UPLOADER_EVENTS.REQUEST_PRE_SEND` listener has `undefined` instead of the `File` I'm trying to upload. It works on 0.13.2.

**To Reproduce**
1. Try to drop a file from your file system

**Expected behavior**
File should start to upload with proper headers in its request.

**Versions**
Chrome - version 0.13.2 works, 0.13.3 fails.

**Code**
```js
const listeners = useMemo(() => ({

  [UPLOADER_EVENTS.REQUEST_PRE_SEND]: async (request: any) => {
  
    const { items } = request;
    
    const fileName = items[0].file.name, // <-- BUG: items[0] is undefined
          slug = `${uuid()}_${fileName}`;
    
    const headers = {
      slug,
      'content-disposition': `attachment;filename="${fileName}"`
    };
    
    return {
      options: {
        destination: {
          headers
        }
      }
    };
  }
}), []);
```

**Comment by yoavniran** [comment]
thanks @creage definitely seems like a bug. 
Curious how none of the automation tests caught this... :( 
Will fix soon

**Comment by yoavniran** [comment]
@creage 0.13.4 is available and should fix the problem.
