### ISSUE TITLE
Next Batch is not previewed till the first Batch is uploaded

### ISSUE THREAD

**Issue by chirag52999** [rpldy/react-uploady#272]
**Next Batch is not previewed till the first Batch is uploaded. **
when we start uploading one batch and while the first batch is uploading select the next batch to upload it has been added to the queue but not displaying/appending with the current batch. 

**To Reproduce**
1. Use <UploadPreview rememberPreviousBatches PreviewComponent={QueueItem} /> for preview . 
2. Start uploading one batch 
3. All lists will be shown and added to components via props. 
4. Select the next  batch to upload which the first batch is uploading 
5. next batch is not shown in the preview component. 

**Expected behavior**
Next batch items should be shown/added to the preview component. 

**Versions**
Specify the versions of the @rpldy packages you're using. 
@rpldy/upload-preview-^0.15.0
@rpldy/uploader-^0.15.0
 @rpldy/uploady-0.15.0
Browser this bug reproduces in - Chrome Version 96.0.4664.55 

**Code**
<UploadPreview rememberPreviousBatches PreviewComponent={QueueItem} />

const QueueItem = memo(props => {
    const [progress, setProgress] = useState(0);
    const [itemState, setItemState] = useState(0);

    useItemProgressListener(item => {
        if (item.completed > progress) {
            setProgress(() => item.completed);
            setItemState(() =>
                item.completed === 100 ? STATES.DONE : STATES.PROGRESS
            );
        }
    }, props.id);

    useItemAbortListener(item => {
        setItemState(STATES.ABORTED);
    }, props.id);

    useItemErrorListener(item => {
        setItemState(STATES.ERROR);
    }, props.id);

    return (
        <PreviewItemContainer state={itemState}>
            <div style={{ display: "inline-block", verticalAlign: "top", width: "95%", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                <ImageName>{props.name}</ImageName> &nbsp;
                <br />
                <span>{progress.toFixed(2)} %</span>
                <br />
                <Line
                    strokeWidth={2}
                    percent={progress}
                    strokeColor={progress === 100 ? "#00a626" : "#2db7f5"}
                />
            </div>
            <div style={{ display: "inline-block", verticalAlign: "top", "width": "5%", paddingLeft: "0px", float: "right" }}>
                <AbortButton id={props.id} state={itemState} />
            </div>
        </PreviewItemContainer> 
    );
});

**Comment by yoavniran** [comment]
Hi @chirag52999 
this isnt a bug but by design. 

However. I do like it as an enhancement request to allow you to choose the event to register to.
In your case you want the `useBatchAddListener` while the current event hook used is: `useBatchStartListener`.

What I'll probably do is make it possible to customize the hook used while keeping the current default so it doesnt change for those who wish to keep current behavior as is.

I will probably have something out in the next few days.
