### ISSUE TITLE
Did not find `clearPendingOnAdd` in docs/api

### ISSUE THREAD

**Issue by musicformellons** [rpldy/react-uploady#322]
I found `clearPendingOnAdd` in some examples, but did not manage to find it in the docs/api. Seems to me it is missing?!

**Comment by yoavniran** [comment]
Yes. Will add it in types and docs. 
thanks!

**Comment by yoavniran** [comment]
added: https://react-uploady.netlify.app/docs/api#clearPendingOnAdd
