### ISSUE TITLE
chunked-sender v0.17.4 fails to slice

### ISSUE THREAD

**Issue by vonderheide** [rpldy/react-uploady#339]
Chunked uploads started to fail after upgrading chunked-uploady from 0.17.3 to 0.17.4.
Now, each chunk fails with "chunk failure - failed to slice".

I tracked this down to sendChunks.js:64. The blob is returned correctly from getChunkDataFromFile, but the setter of chunk detects that the proxy is unmodifiable and ignores the data. This causes the next line to throw a ChunkedSendError.

0.17.3 works fine - it looks like the proxy was introduced for 0.17.4.

Let me know if I can further help with debugging.

**Comment by yoavniran** [comment]
thanks @vonderheide 
I actually just fixed this issue and am releasing the fix now (0.17.5)
I think it only affects dev time and not production builds but nonetheless, the fix will be out shortly

**Comment by vonderheide** [comment]
Thanks, that was quick :-)
Yes, it looks like this will not happen if isProduction() returns true.

**Comment by yoavniran** [comment]
@vonderheide 0.17.5 is out now. Please let me know if fixed or if you experience issues still.
