### ISSUE TITLE
useItemErrorListener() does not trigger when using a mock sender for unit tests

### ISSUE THREAD

**Issue by AJLemos** [rpldy/react-uploady#348]
**Describe the bug**

When using `getMockSenderEnhancer()` for unit tests, the `useItemErrorListener()` hook is not triggered when setting an error code to the mock enhancer. For example `getMockSenderEnhancer({ responseStatus: 500 })`.

**To Reproduce**
1. Create a unit test using `getMockSenderEnhancer()` for a hook or component which uses the `useItemErrorListener()` hook
2. Set `responseStatus` to an error code, such as `500`
3. Expect the `useItemErrorListener()` hook is fired in the mock and items are updated with a status of "error"

**Expected behavior**

When `responseStatus` is set to an error status code in the mock sender enhancer, the `useItemErrorListener()` hook is triggered and the item's status is set to "error".

**Versions**

@rpldy/uploady: 0.17.5

**Code**

Here is a codesandbox running a simplified failing test example: https://codesandbox.io/s/throbbing-resonance-oez2tc?file=/src/useUploaderExample.test.js

I'm not very familiar with the mock internals yet, but I did notice that the Batch Items state is being set to `FILE_STATES.FINISHED` (here: https://github.com/rpldy/react-uploady/blob/master/packages/core/mock-sender/src/mockSender.js#L118), even when the mock is given an error code for the `responseStatus`. Setting the Batch Item state to `FILE_STATES.ERROR` when a failing `responseStatus` is provided should fix the Bath Item's state. However I'm not sure if setting this to `FILE_STATES.ERROR` would result in the `useItemErrorListener()` hook being triggered in the mock state or not.

Here is the example code in the codesandbox:

`useUploaderExample.js`

```js
import { useState } from 'react';
import { useBatchAddListener, useItemErrorListener, useItemFinishListener } from '@rpldy/uploady';

/**
 * @returns {{
 *   failedItems: BatchItem[],
 *   finishedItems: BatchItem[],
 *   items: BatchItem[],
 * }}
 */
export default function useUploaderExample() {
  let [ items, setItems ] = useState(/** @type {BatchItem[]} */ ([]));
  let [ failedItems, setFailedItems ] = useState(/** @type {BatchItem[]} */ ([]));
  let [ finishedItems, setFinishedItems ] = useState(/** @type {BatchItem[]} */ ([]));

  useBatchAddListener(({ items: newItems }) => {
    setItems([ ...items, ...newItems ]);
  });

  useItemErrorListener((item) => {
    setFailedItems([ ...failedItems, item ]);
  });

  useItemFinishListener((item) => {
    setFinishedItems([ ...finishedItems, item ]);
  });

  return {
    items,
    failedItems,
    finishedItems,
  };
}

/** @typedef {import('@rpldy/uploady').BatchItem} BatchItem */
```

`useUploaderExample.test.js`

```js
/* eslint-env jest */
import { renderHook } from "@testing-library/react-hooks/dom";
import { getMockSenderEnhancer } from "@rpldy/mock-sender";
import Uploady, { useUploady } from "@rpldy/uploady";

import useUploaderExample from './useUploaderExample';

describe('useUploaderExample()', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  test('returns failed batch items', async () => {
    let context;

    const GetContext = () => {
      context = useUploady();
      return null;
    };

    let enhancer = getMockSenderEnhancer({
      delay: 400,
      // BatchItem uploads should have a status of "failed" and trigger the
      // `useItemErrorListener()` hook
      responseStatus: 500,
      response: { mock: true, success: false },
    });

    let { result, waitForNextUpdate } = renderHook(() => useUploaderExample(), {
      wrapper: ({ children }) => (
        <Uploady
          concurrent={true}
          enhancer={enhancer}
          maxConcurrent={1}
          multiple={true}
          noPortal={true}
        >
          <GetContext />
          {children}
        </Uploady>
      ),
    });

    context.upload('testFile');

    await waitForNextUpdate();

    expect(result.current.items).toHaveLength(1);

    await waitForNextUpdate();

    // Expected state, due to `responseStatus: 500` in the mock enhancer.
    expect(result.current.failedItems).toEqual([
      expect.objectContaining({
        id: 'batch-1.item-1',
        state: 'error',
      }),
    ]);

    // Actual state
    // expect(result.current.finishedItems).toEqual([
    //   expect.objectContaining({
    //     id: 'batch-1.item-1',
    //     state: 'finished',
    //   }),
    // ]);
  });
});
```

**Comment by yoavniran** [comment]
Hi @AJLemos 

Thanks for the very detailed issue description!

I recently added the [isSuccessfulCall](https://react-uploady.netlify.app/docs/api/#issuccessfulcall) prop that can be used to customize the sender's logic deciding whether a request was successful or not.

I will pass it to the mock sender so you can use it in your tests. 
I should be able to release this in the next couple of days

**Comment by AJLemos** [comment]
Fantastic. I look forward to testing it out. Thanks for the reply.

**Comment by AJLemos** [comment]
This worked well for our unit test coverage. Thanks for the addition!

**Comment by yoavniran** [comment]
glad to hear @AJLemos !
