### ISSUE TITLE
Uploady - Valid UploadyContext not found. Make sure you render inside <Uploady>

### ISSUE THREAD

**Issue by Hocdoc** [rpldy/react-uploady#376]
**Describe the bug**

When I use the example for `asUploadButton` from https://react-uploady.org/docs/api/hocs/asUploadButton/#example I get the following error.

```
Unhandled Runtime Error
Invariant Violation: Uploady - Valid UploadyContext not found. Make sure you render inside <Uploady>

Call Stack
invariant
node_modules/invariant/browser.js (38:0)
assertContext
node_modules/@rpldy/upload-button/node_modules/@rpldy/shared-ui/lib/esm/assertContext.js (9:11)
useUploadyContext
node_modules/@rpldy/upload-button/node_modules/@rpldy/shared-ui/lib/esm/hooks/useUploadyContext.js (5:46)
AsUploadButton
node_modules/@rpldy/upload-button/lib/esm/asUploadButton.js (10:25)
...
```

- When using V. 0.14.1 of the uploader packages everything works fine.
- After updating to V. 1.0.0 the error occures. I have already tried to remove `node_modules` and reinstall all packages.

**Versions**

- "@rpldy/upload-button": "^1.0.0",
- "@rpldy/uploader": "^1.0.0",
- "@rpldy/uploady": "^1.0.0",
- Chrome

**Comment by yoavniran** [comment]
Hey @Hocdoc I'll need a reproducing code example as I cannot reproduce it myself.
See this codesandbox - https://codesandbox.io/s/react-uploady-asuploadbutton-9ycrc

It uses 1.0.0 and the "button" works as expected.

**Comment by Hocdoc** [comment]
Hm you are right, this minimal example works.

In my bigger code base the update didn't worked as expected even after spending hours about this issue. 
I will stay with V. 0.14.1 and try to find the error and create a minimal not-working example in the next weeks. In the meantime I close the issue.

Thanks for your effort!

**Comment by yoavniran** [comment]
@Hocdoc Id suggest starting with `yarn why` on the @rpldy/* packages. This error is almost always related to multiple versions being installed.
