### ISSUE TITLE
Uncaught TypeError when uploads are aborted while still processing in `useRequestPreSend()`

### ISSUE THREAD

**Issue by AJLemos** [rpldy/react-uploady#379]
**Describe the bug**

[useRequestPreSend()](https://react-uploady.org/docs/api/hooks/userequestpresend/) can return a promise. This is useful when each upload requires asynchronous processing before uploading actually begins. Some use case examples might be making a network request to check for duplicate files before uploading the actual binary, or creating a hash of the file to send with the upload for validation.

When an upload is aborted while `useRequestPreSend()` is asynchronously processing, the following error occurs when the async process completes and `useRequestPreSend()` returns a `Destination` object.

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'finishedCounter')`

**To Reproduce**

I've set up a code sandbox to demonstrate the issue: 

1. Go to https://codesandbox.io/s/uploady-abort-error-kqk6xz?file=/src/RequestPreSend.js
2. Click on `Upload Files` and select a file
3. Click on `Abort Upload` within 10 seconds
4. Wait for the 10 second timer in `useRequestPreSend()` to complete and return a `Destination` object for the upload (this is just to simulate some real-world asynchronous processing)
5. See the error, which looks like it happens [here](https://github.com/rpldy/react-uploady/blob/master/packages/core/uploader/src/queue/batchHelpers.js#L245)

**Expected behavior**

- There is no Uncaught TypeError.
- The Uploady hooks, such as `useItemAbortListener()`, `useItemCancelListener()`, `useItemErrorListener()`, etc only fire a single event for the aborted item (I assume in the abort listener).

**Versions**
```
    "@rpldy/retry-hooks": "1.0.0",
    "@rpldy/upload-button": "1.0.0",
    "@rpldy/upload-drop-zone": "1.0.0",
    "@rpldy/uploady": "1.0.0",
```
I've reproduced the bug in Chrome, but I assume it happens in all browsers.

**Code**

https://codesandbox.io/s/uploady-abort-error-kqk6xz?file=/src/RequestPreSend.js

**Comment by yoavniran** [comment]
thanks for reporting @AJLemos 
will look into it

**Comment by yoavniran** [comment]
@AJLemos version 1.0.1 is now out
