### ISSUE TITLE
Resetting state

### ISSUE THREAD

**Issue by dbousamra** [rpldy/react-uploady#39]
What is the recommended way to reset the uploader. I.e. a user has uploaded a bunch of items, and they want to clear the finished batch(es) and start afresh. I guess I could trigger a complete remount of the component somehow.

**Comment by yoavniran** [comment]
there is currently no explicit way to reset the uploader. I considered it but didnt come up yet with a solid use-case.
The upload information (batches, items) is cleaned upon completion by the uploader internals.

**Comment by dbousamra** [comment]
Okay. What is your recommended approach then?

**Comment by yoavniran** [comment]
again, not sure what's the use case. 
indeed, re-rendering the <Uploady> component will cause a "reset" but I don't think its needed. You should be fine with rendering it once and letting it live.

**Comment by getsetbro** [comment]
What is the best way tell the component to quit showing the progress-bar when the upload is done? Thanks

**Comment by yoavniran** [comment]
@getsetbro Id be happy to answer but feel its less effective here. Can you ask on stackoverflow? That way its more findable for future reference as well

**Comment by getsetbro** [comment]
@yoavniran Sure. https://stackoverflow.com/questions/65599743/recommended-way-to-stop-showing-progress-with-react-uploady

**Comment by dexi-1bit** [comment]
I am looking for this one as well.

Currently I am using an MUI Modal.

1. I open up a modal then click upload button, select a file. --- OPTION is autoUpload = false

2. Then I suddenly decided to close the MUI Modal.

3. When I open up the modal the file is still there, but now I need to call my api to post something but without video file this time.

**Comment by yoavniran** [comment]
hey @dexi-1bit 
sounds like the [clearPending](https://react-uploady.org/docs/api/context/#clearpending) context method should help with that.

**Comment by dexi-1bit** [comment]
> hey @dexi-1bit sounds like the [clearPending](https://react-uploady.org/docs/api/context/#clearpending) context method should help with that.


Hi thanks for the reply @yoavniran 

I tried to use clearPending() but when I call uploady.getInternalFileInput() it still shows that there is a file.

![image](https://user-images.githubusercontent.com/124560514/236741202-f6d03d78-17ca-442c-8b6e-5a758f37e5cf.png)

**Comment by yoavniran** [comment]
ok. but how does that influence your app? 
if you use uploady to select additional files later on, this selection will be overriden
