### ISSUE TITLE
Uploady Context upload and abort methods issues

### ISSUE THREAD

**Issue by alonfai** [rpldy/react-uploady#40]
I'm creating an object for the uploadyContext API and trying to simulate events inside the context listener hooks, but neither seems to be working.

1. having `autoUpload = false` in the <Uploady /> component wrapper and calling uploadyContext.upload(batchId) => fail 
2. having `autoUpload = true` in the <Uploady /> wrapper and calling uplodyContet.abort(itemId) => fail

```
import {  
  useBatchStartListener,
  useBatchFinishListener,
  useItemStartListener,
  useItemFinishListener,
  useItemProgressListener,
  useBatchAbortListener,
  useBatchCancelledListener,
  useItemAbortListener,
  useItemCancelListener,
  useBatchAddListener,
  useItemErrorListener
, UploadyContext } from '@rpldy/uploady';
import { Batch, BatchItem } from '@rpldy/shared';

// .... Inside my React component ... //

const uploadyContext = React.useContext(UploadyContext);

useBatchAddListener((batch: Batch) => {
   console.warn(`batch ${batch.id} was just added with ${batch.items.length} items`);
    uploadyContext.upload(batch.items[0].batchId); // Calling with the batchId or should be by itemId ?
  });

useItemStartListener((item: BatchItem) => {
    // Cancel the upload if given file already exceeds the maximum files allowed or the size of any       
   console.warn(`item ${item.id} started uploading`);  
    uploadyContext.abort(item.id);
});


useItemProgressListener((item: BatchItem) => {
  console.warn(
      `item ${item.id} File ${item.file.name} is ${item.completed}% done and ${item.loaded} bytes uploaded`
    );

// Despite calling`abort` at the itemStartEvent above, the web socket continues with the upload
});

**Comment by yoavniran** [comment]
Hey Alon,
Can you add some information on what exactly you're trying to achieve? not sure I follow.
Why are you calling abort? 
why are you trying to use autoUpload = false?

But I can share a few things that hopefully will be helpful:

uploadyContext.upload is for adding a new file to be uploaded so it should be called with a File object generally.

It's currently not possible to make pending uploads (when autoUpload = false) start from the UploadyContext which is an oversight. I will fix that shortly.

cancelling uploads can be done by returning false from the useBatchAddListener, useBatchStartListener or useItemStartListener hooks.

there's also the fileFilter upload option which can be used to filter out certain files from the batch.

**Comment by alonfai** [comment]
Hi Yoav,

I'm working on a requirement for the client to be able to add files to a collection and manually triggers the upload process with an event on a button click. Hence why I use autoUpload=false and trying to mimic the upload using the context object (will wait for your new version with the fix) 

The cancelling of the upload in any of the hooks worked as you suggested 👍 

I believe it will be good to add more description in the docs for these scenarios (especially canceling uploads), plus updating the typescript definitions both for the context upload and canceling (for instance, currently the hooks expect to return a `void` which is confusion).

```
type EventHook<T> = (cb: (obj: T) => void) => void;
type CancellableHook<T> = (cb: (obj: T) => boolean | void) => void;
type EventHookWithState<T> = (cb?: (obj: T) => void) => T;

```

**Comment by yoavniran** [comment]
thanks for the feedback Alon!

version 0.1.12 is now published and includes the missing function: 
https://github.com/rpldy/react-uploady/tree/master/packages/ui/uploady#processpending

I will review the doc and see how i can clarify or add more info so its easier to follow.

as for the type defs. Not sure I understand the issue. 
Notice that the hook itself doesnt return anything (unless its a stateful hook).

For events that can cancel an upload - the callback the hook receives may return either boolean (false) or nothing (void) which is defined for the CancellableHook

take for example: 

```javascript 
   useItemStartListener: ItemCancellableEventHook
   //->
   type ItemCancellableEventHook = CancellableHook<BatchItem>;
  //->
  type CancellableHook<T> = (cb: (obj: T) => boolean | void) => void;
```
Hope it makes sense

**Comment by alonfai** [comment]
Works well now, thanks.

For reference, what happens if I created several batch instances (e.g.: open the upload screen, select few files, closing it and reopen it again to select extra files that were not picked in the first time), will the `processing` method takes all files in all batches added or only the latest?

**Comment by yoavniran** [comment]
all pending batches will be uploaded
