### ISSUE TITLE
Typings mismatch of retry-hooks package

### ISSUE THREAD

**Issue by mathijsco** [rpldy/react-uploady#407]
**Describe the bug**
The typings of the retry-hooks package do not match the functionality.

The hook `useRetry` and `useBatchRetry` are missing the second argument to provide the options.
This is regarding the types `RetryMethod` and `RetryBatchMethod`.

The callback of the hook `useRetryListener` contains a parameter of type `RetryEventData`. This type has an items collection of `string[]`. However it should be `BatchItem[]`.

**To Reproduce**
1. Install the packages `@rpldy/uploady@1.1.0` and `@rpldy/retry-hooks@1.1.0`.
2. Start Visual Studio 2022.
3. Use the code below and notice the errors.

**Expected behavior**
The typings should match the javascript code.

**Versions**
@rpldy/uploady@1.1.0
@rpldy/retry-hooks@1.1.0
Running in Visual Studio Professional 2022.

**Code**
```ts
import * as React from "react";
import { BatchItem } from "@rpldy/uploady";
import { useRetry, useRetryListener } from "@rpldy/retry-hooks";

export const MyUploadComponent: React.FC = () => {
    useRetryListener((data) => {
        // The items are not strings but BatchItems
        const retryItems = data.items as unknown as BatchItem[];

        // Do some things with the items...
        // ERROR HERE. data.items[0] is a string according the typings
        console.log(`Item: ${data.items[0].id}`);
    });
	
    const retryItems = useRetry();

    const onRetryAllItems = () => {
        // ERROR HERE. The second options parameter is not allowed.
        retryItems(undefined, {
            destination: {
                headers: { authorization: "Bearer MySuperSecretToken" },
            },
        });
    };

    return (<div></div>);
};
```

**Comment by yoavniran** [comment]
thanks @mathijsco 
I will look into this shortly

**Comment by yoavniran** [comment]
@mathijsco [1.2.0 released](https://github.com/rpldy/react-uploady/releases/tag/v1.2.0)
