### ISSUE TITLE
FileFilterMethod typescript definition wrong

### ISSUE THREAD

**Issue by lughino** [rpldy/react-uploady#425]
> Recommended - Check out the [discussions area](https://github.com/rpldy/react-uploady/discussions) before opening a new issue.

**Describe the bug**
The typescript definition of [`FileFilterMethod`](https://github.com/rpldy/react-uploady/blob/master/packages/core/shared/types/index.d.ts#L13) seems to be wrong.
It states that accepts 3 arguments, but it receives [only one argument](https://github.com/rpldy/react-uploady/blob/master/packages/core/uploader/src/batch.js#L24).

The typescript signature is actually useful.
I was trying to filter the number of files accepted when I drag multiple files.
The problem is that there is no way for me to know how many files have been already added to the batch, and the `multiple` option works only on file input, so I cannot limit the number of files uploaded when the user use the drag and drop feature.

**To Reproduce**
Check [`FileFilterMethod`](https://github.com/rpldy/react-uploady/blob/master/packages/core/shared/types/index.d.ts#L13) with the [actual implementation](https://github.com/rpldy/react-uploady/blob/master/packages/core/uploader/src/batch.js#L24).

**Expected behavior**
Receive the other two arguments in order to successfully filter the files when using drag and drop

**Versions**
1.2.0

**Code**
Please provide code sample or better yet, a link to a reproducing repository or best yet, codesandbox (fiddle, etc) where issue can be reproduced easily

**Comment by yoavniran** [comment]
thanks @lughino, good catch.
I will add a fix to the 1.3.0 RC shortly.
