### ISSUE TITLE
Please release the latest commits

### ISSUE THREAD

**Issue by klfman** [rpldy/react-uploady#443]
I don't know if this is the right way, but I did not find any other:

Would you please be so kind to trigger a release, as the latest commit on master (https://github.com/rpldy/react-uploady/commit/f0fd905b1687cbc9a206fe476619f60d804438c9) fixes a problem that I'm having and has not yet been released.

I would love to just install it with npm.

**Comment by yoavniran** [comment]
@klfman done :)
