### ISSUE TITLE
Not working with edge runtime

### ISSUE THREAD

**Issue by zhuhaow** [rpldy/react-uploady#495]
The below code expect either `window` or `process` is available, i.e., either the code is executed in browser or node env.

https://github.com/rpldy/react-uploady/blob/73af9f79bae465b678167b4da6217cb3f38d2204/packages/ui/shared/src/uploadyVersion.js#L15-L19

However, with [edge runtime](https://common-min-api.proposal.wintercg.org), e.g., Cloudflare workers, we may have neither of them, which would cause error 

```
ReferenceError: process is not defined
```

We probably should use `globalThis` for this use case https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#description

**Comment by yoavniran** [comment]
thanks @zhuhaow 
I will take a look. Definitely seems like an improvement.

Is there a specific use-case you envision Uploady being used on edge? Would love to hear more.

**Comment by zhuhaow** [comment]
I'm using Cloudflare Pages with Remix to do server-side rendering on edge.

**Comment by yoavniran** [comment]
Hey @zhuhaow 
version [1.4.1-rc.0](https://github.com/rpldy/react-uploady/releases/tag/v1.4.1-rc.0) is out with a fix. Can you please check and let me know if it works ok?

**Comment by zhuhaow** [comment]
Sorry for the delayed reply. 

Yes! It's fixed now. Thanks.

**Comment by yoavniran** [comment]
great, thanks @zhuhaow 
Will release 1.4.1 shortly
