### ISSUE TITLE
Clicking to crop image using react-image-crop makes the image disappear

### ISSUE THREAD

**Issue by x-N0** [rpldy/react-uploady#523]
I'm opening and closing this "bug report" to prevent someone loosing a lot of time researching why using react-image-crop to emulate the behavior in the react-uploady preview with form example, when clicking the image to start the cropping the image disappears.

The reason is that there's a bug in the latest versions of  react-image-crop there's no onImageLoaded, so the onLoad callback is never being called.

The version I found working is  react-image-crop@^8.6.12

**Comment by yoavniran** [comment]
thanks @x-N0 
They in fact made breaking changes in their 10.0.0 release - https://github.com/DominicTobias/react-image-crop/releases/tag/10.0.0-beta.0
