### ISSUE TITLE
use*ProgressListener reports uneven completed percentage when files are different sizes

### ISSUE THREAD

**Issue by jobh** [rpldy/react-uploady#546]
**Describe the bug**

The `use*ProgressListener` hooks seems to report incorrect progress (completed%) in the following cases:

1. `useBatchProgressListener` when there are both small and large files in the batch,
2. `useItemProgressListener` when there are both small and large files in a group. [*]

In the first case, I have been able to recover the correct progress by inspecting the individual items' progress. In the second case, I am not sure how to get the correct value since the individual items' progress is also wrong.

[*] Note - perhaps I should only claim that the individual items' progress is wrong during `useBatchProgressListener`

**To Reproduce**

1. Install a `useBatchProgressListener` and log `batch.completed`
2. Upload a set of some large and some small files. In my case, the files range from hundreds of kB to hundreds of MB.

**Expected behavior**
I expect `completed` to increase smoothly.

_Case 1_. This is a batch without grouping. Every 20 progress events I log the value of the workaround below (left) and the `batch.completed` value (right). Notice the "workaround" value increases smoothly, but the `batch.completed` value quickly jumps to 98%+.

|workaround|batch.completed|
|---|---|
|0|5|
|10|30|
|25|50|
|32|66|
|40|87|
|52|98|
|70|99|
|87|100|
|100|100|

_Case 2_. This is a batch _with_ grouping. Every 20 progress events I log the value of the workaround below (left) and the `batch.completed` value (right). Neither the "workaround" value based on items' progress nor the `batch.completed` value are smooth, although they are very different.

|workaround|batch.completed|
|---|---|
|0|0|
|25|53|
|27|53|
|29|54|
|31|55|
|100|82|
|100|100|

**Versions**

```
@rpldy/uploady@1.4.1
Chromium	116.0.5845.96 (Official Build) snap (64-bit)
```

**Code**

Workaround described above, that works for case (1):
```
    const progress = useBatchProgressListener(id);
    const [sentx100, total] = progress?.items.reduce(
        (acc, item) => {
            acc[0] += item.file.size * item.completed;
            acc[1] += item.file.size;
            return acc;
        },
        [0, 0],
    ) ?? [0, 1];
    const completed = sentx100 / total;
```

**Comment by yoavniran** [comment]
hey @jobh 
thanks for the detailed description. Looks like an issue to handle.
I will investigate and fix soon

**Comment by yoavniran** [comment]
@jobh 
[1.5.0-rc5](https://github.com/rpldy/react-uploady/releases/tag/v1.5.0-rc.5) is now available. Please give it a try. I think I managed to improve the progress "smoothness" as you suggested.
From my tests, its still not 100% due to the way progress is reported by the browser (through XHR). Sometimes a single file jump from 0 to 3+ MB without any value in the middle 🤷
