### ISSUE TITLE
Support for userData in upload options

### ISSUE THREAD

**Issue by jobh** [rpldy/react-uploady#547]
**Is your feature request related to a problem? Please describe.**

It would be very nice to be able to attach user data to an upload (batch). An example is shown below. Note, *this already works*, but it feels hacky and is not explicitly supported, plus it is contrary to the typescript definitions.

**Describe the solution you'd like**

```
const { upload } = useUploadyContext();
const handleDrop = (files) => {
    const projects = deriveProjectsFromFiles(files);
    projects.forEach((project) => upload(project.files, { userData: { project } } )
};
```
and then
```
    useBatchAddListener((batch, options) => {
        const { project } = options.userData;
        handleAddRow({ id: batch.id, name: project.name });
    });
```

**Describe the solution you'd like**

I think that adding a typescript definition
```
userData?: object;
```
on `UploadOptions` would be sufficient, implicitly declaring this as supported and also making TS happy.

**Describe alternatives you've considered**

The current situation (works but is unsupported) is actually ok with me, I'm registering this issue in case you'd like to declare it supported — because I think it would be a useful feature.

**Comment by yoavniran** [comment]
Hey @jobh why not use the [Params](https://react-uploady.org/docs/api/#params) property of the UploadOptions?

**Comment by jobh** [comment]
> why not use the [Params](https://react-uploady.org/docs/api/#params) property of the UploadOptions?

Hi @yoavniran,

The reason is that I don't want to send the user-data object as a request parameter. I only need it internally on the frontend, to associate the upload batch with the underlying object that is being uploaded (`project` in my example). This is for example to populate an upload table with both project name and batch-id (for progress/abort purposes).

**Comment by yoavniran** [comment]
got it. sounds reasonable. I will give it some thought and most likely add it very soon

**Comment by jobh** [comment]
Thanks @yoavniran!
