### ISSUE TITLE
tus-uploady: Support destination headers & clarify readme

### ISSUE THREAD

**Issue by kevbost** [rpldy/react-uploady#60]
I noticed while trying to implement this package that the tus-uploady readme states:

```bash
# packages/ui/tus-uploady/README.md L63
It also supports the Upload-Metadata header and will turn the destination params prop into the metadata key/value.
```

Headers aren't passed through with the prop `destination={{url: "https://my-server", headers: {"x-custom": "123"}}}` even though the Readme states `all UploadOptions props can be passed to TusUploady`.

I would suggest either allowing custom headers or updating the Readme to make the `params` object more clear in the props table.

I'd also suggest making it clear that you don't have to pre-encode the Upload-Metadata values in Base64 as is required in the [TUS Docs concerning the Upload-Metadata format](https://tus.io/protocols/resumable-upload.html#upload-metadata). The destination `params: {key: 'value'}` is automatically converted to `Upload-Metadata: key dmFsdWU=`.

**Comment by yoavniran** [comment]
hey @kevbost 

re headers - this is unexpected. destination.headers should be passed afaik. Sounds like a bug, ill check.

re params - these are generic params that are either sent as form data (when used with normal Uploady or Chunked-Uploady) or converted to the TUS Upload-Metadata header. What do you feel is missing?

re params - encoding. Will do. 

thanks

**Comment by kevbost** [comment]
I don't feel anything else is missing, I'm only suggesting that the docs on the topic need to be a little more explicit. Thank you!

**Comment by yoavniran** [comment]
@kevbost Seeing as TUS uploads first start with a _create_ call and then subsequent chunks each get their own request, youd expect the custom header to be sent along with the _create_ call, I presume?
