### ISSUE TITLE
Batch progress completion incorrect when using mock sender

### ISSUE THREAD

**Issue by mwdiaz** [rpldy/react-uploady#626]
**Describe the bug**
As of v1.5.0 (I believe due to the change made in #566), the `completed` property for a given Batch when using `useBatchProgressListener` reports the incorrect percentage if also using a mock sender.

I think this is due to using the underlying file's size [here](https://github.com/rpldy/react-uploady/pull/566/files#diff-b1b522987cb1ef3506a148f8eb460de9c9311147064ea07f1dd1257555bb994eR111) when determining the total size of the batch. When using a mock sender, the file size is determined by the `fileSize` option passed to `getMockSenderEnhancer`, but there is still a real underlying File object that will report the correct size and not the mocked size.

It might be nice if the progress timers for each mocked request _did_ use the actual file size instead of a hard-coded value in the mock sender, since that might add a dash of realism to interactive examples in Storybook, but I understand if that isn't feasible for technical reasons. Regardless, having the batch progress work accurately in this scenario (as was the case prior to v1.5.0) is useful for us since where we display an overall progress bar along with individual item progress bars and use a mock sender in our design system (Storybook / Chromatic).

**To Reproduce**
1. Create an Uploader with a mock sender enhancer (for example, following the example on the [API docs page](https://react-uploady.org/docs/api/senders/mockSender/) for `mockSender`)
2. In a child component of `<Uploader>`, utilize the `useBatchProgressListener` hook and observe that the `completed` property for the batch is incorrect, given the progress intervals for the file being "sent"

**Expected behavior**
Batch progress should accurately reflect mocked items progress intervals when using `mock-sender`.

**Versions**
v1.5.0+

**Code**
Here's a simple CodeSandbox demonstrating the issue: https://codesandbox.io/s/muddy-dream-7jy765. If the `@rpldy/*` dependencies are reverted to 1.4.1. or earlier, the behavior will be as expected.

**Comment by yoavniran** [comment]
hey @mwdiaz 
Thanks for the detailed & complete bug report 👍 
Will fix very soon

P.S. When I wrote the mock-sender I mostly thought about Uploady internal tests and faster dev time for the library. Its really cool to see that others use it as well and it makes a lot of sense, of course.

**Comment by mwdiaz** [comment]
Thanks! Yeah, the mock sender has been great for us; both in interactive Storybook examples as well as unit tests.

**Comment by mwdiaz** [comment]
Thanks! I'm out of the office on vacation, but will definitely check it out when I'm back next week.

**Comment by mwdiaz** [comment]
Just tried it out and things look better! One thing I've noticed is that for batch progress events the `completed` value is [not multiplied by 100 ](https://github.com/rpldy/react-uploady/blob/bb1e2d2c7166ebaabb81b0a8dd6fd09a472a081a/packages/core/uploader/src/queue/uploaderQueue.js#L126)before being passed to the consumer, [which is different from items](https://github.com/rpldy/react-uploady/blob/bb1e2d2c7166ebaabb81b0a8dd6fd09a472a081a/packages/core/uploader/src/batchItemsSender.js#L26). Is there a technical reason for that, or could the behavior be standardized? I can see it being a potential source of confusion.

Thanks for the quick fix, when do you think a non-RC version might be made available on npm?

**Comment by yoavniran** [comment]
Hope you had a nice vacation Mike.
Will look into the progress inconsistency. I see that it was like that before the fix but should be easy enough to align.
I'll probably release 1.7.0 this weekend.

**Comment by yoavniran** [comment]
actually, the inconsistency isnt related to the mock-sender specifically. 
In this case I wont be changing it at this point, it may impact too many existing implementations. 
Something for v2 perhaps :)

**Comment by yoavniran** [comment]
release [1.7.0](https://github.com/rpldy/react-uploady/releases/tag/v1.7.0) is now available
