### ISSUE TITLE
Chunked Uploady does not support UploadButton

### ISSUE THREAD

**Issue by deepakgogia** [rpldy/react-uploady#64]
I am using chunked upload feature but getting error Invariant Violation: Uploady - valid UploadyContext not found. Make sure you render inside <Uploady>.

I have resolved above error with to import chunkedUploady through "@rpldy/uploady".

I have gone through the code and  found that uploady is returning from chunkeduploady, so why i am getting this error.

Now chunkedSize and chunked are not supported by chunkeduploady.

Here is my code...

import ChunkedUploady from "@rpldy/uploady";
import { useContext } from 'react';

import { UploadyContext } from '@rpldy/uploady';

const UploadContent = () => {
    return (
< ChunkedUploady
        chunkSize={2142880}
        chunked={true} >

            < UploadButton1 />

    < /ChunkedUploady>);
}
export default UploadContent;

const UploadButton1 = () => {
    const uploady = useContext(UploadyContext);
    let url = null;
    
    const onClick = async () => {
        try {
            if (!url) {
                await apiGetSignedUploadUrl(idType)
                    .then((out) => {
                        const { success, data } = out;
                        if (success) {
                            url = data.uploadUrl;
 
                        }
                    })
            }
            uploady.showFileUpload({
                destination: {
                    url,
                    method: 'PUT',
                    headers: {
                        "Content-Type": '',
                    },
                },

                sendWithFormData: false,
            });

        } catch (error) {
            console.error(error, error.response);
            throw error;
        }
    }

    return <>
        <Button type='button'
            onClick={onClick}
            style={{
                border: isError ? '1px solid red' : '1px solid rgba(166, 125, 255, 0.5)',
                color: isError ? 'red' : '#a67dff'
            }}
        >
            {getUrl ? successCaption : 'Upload'}</Button>
        <div>
            <span style={{ color: isError ? 'red' : '#a67dff' }}>{isError ? errMsg : ''}</span>
        </div>
    </>
}

-------------------------

Thanks in advance!!

**Comment by yoavniran** [comment]
Hey @deepakgogia 

Im not sure exactly what problem you're having with chunked-uploady.
It would be easier to troubleshoot if you could provide it in something like codepen or codesandbox.

As you can see in [storybook](https://react-uploady-storybook.netlify.app/?path=/story/chunked-uploady--simple), there shouldnt be any problem using rpldy components/hooks rendered under <ChunkedUploday>

I've also created this [sandbox](https://codesandbox.io/s/react-uploady-chunked-example-ltqfr?file=/src/UploadContent.js). Check it out. I took most of your code and re-wrote it to make better use of the rpldy API. This way you dont need to create your own button component and use the showFileUpload context API. 
You're of course free to use it as its part of the public API, but I'd recommend using the more friendly components and hooks. 

If you do wish to create your own upload button component. There is the [asUploadButton](https://github.com/rpldy/react-uploady/tree/master/packages/ui/upload-button#custom-upload-button-asuploadbutton) HOC, which can be useful as well.

**Comment by deepakgogia** [comment]
Thanks for your help..

I was getting error due to version mismatched of uploady/chunked-uploady/upload-button, now it is working fine.

Is there any way to use dropzone instead of upload-button? because i have two scenarios where i want to use as button and drop zone

**Comment by deepakgogia** [comment]
I am using uploady dropzone feature but i want user can drag/drop or click to upload his files. Can we achieve the same?

**Comment by yoavniran** [comment]
Hey @deepakgogia 
It would have been possible to use both UploadButton and UploadDropZone but I also wanted to check if you could combine them as you suggested.

See this sandbox - https://codesandbox.io/s/react-uploady-dnd-asuploadbutton-jk9bg?file=/src/App.js

Notice, that you do need to **upgrade** the rpldy deps to **0.3.2**.

**Comment by deepakgogia** [comment]
Yes, that example is perfectly working fine for me.

But i also want files information that user will upload.

fileFilter method will return boolean but is there any direct way to apply fileType and files size and video duration.

see this -> _https://codesandbox.io/s/react-uploady-dd-btn-x1zrv?file=/src/App.js_

**Comment by yoavniran** [comment]
fileFilter gives you the ability to filter out files. 
any of the event hooks gives the ability to inspect the file(s) being uploaded: 
https://github.com/rpldy/react-uploady/tree/master/packages/ui/uploady#hooks
