### ISSUE TITLE
export `getPreviewsLoaderHook` for public use

### ISSUE THREAD

**Issue by CanRau** [rpldy/react-uploady#646]
**Is your feature request related to a problem? Please describe.**
I'm building an upload experience for our lexical editor and would love to directly use `getPreviewsLoaderHook` instead of `<UploadPreview/>` or having to unnecessarily rebuild the logic myself as everything is already there 😇 

**Describe the solution you'd like**
Export `getPreviewsLoaderHook` to make it publicly available 🙏
Hope it's not considered an implementation detail 🤞🏼 

**Describe alternatives you've considered**
Rebuilding the generation of preview myself

**Comment by CanRau** [comment]
Might still be nice, though I'm not just using a couple of lines to generate them myself and am good to go, forget sometimes that it's not that hard 😅

**Comment by yoavniran** [comment]
hey @CanRau 
thats an interesting idea. I will consider it for the next minor version.
thanks

**Comment by yoavniran** [comment]
done in #666

**Comment by yoavniran** [comment]
now available in [1.8.0](https://github.com/rpldy/react-uploady/releases/tag/v1.8.0)
