### ISSUE TITLE
Initial Post Request doesnt set header "Upload-Concat": "partial" when parallel is >1

### ISSUE THREAD

**Issue by mariusschroeterCP** [rpldy/react-uploady#685]
We are using an implementation of the tusdotnet package as our tus server. 

When uploading a new video file from the client with react-uploady with following settings:

```
<TusUploady
      key={authCtx.authUser?.userId}
      autoUpload={false}
      multiple={false}
      accept="video/*"
      enhancer={enhancer}
      forgetOnSuccess={true}
      chunkSize={8_000_000}
      parallel={4}
/>
```

We saw a difference from the package "https://github.com/tus/tus-js-client", which we are using on a different project:

### Tus-JS-Client Headers
<img width="765" alt="tus-js-client-parallel-upload" src="https://github.com/rpldy/react-uploady/assets/162111300/68171378-697e-4513-b59f-a8bb0a85805e">

### Uploady
<img width="755" alt="tus-uploady-parallel-upload" src="https://github.com/rpldy/react-uploady/assets/162111300/b2d4cd47-8c8b-468a-b7e0-030397eb9757">

**Expected Behavior**
The POST requests should have the correct "Upload-Concat" Header ("partial", and "final" for the summarized file).

**Versions**
"@rpldy/mock-sender": "^1.8.0",
"@rpldy/retry-hooks": "^1.8.0",
"@rpldy/tus-uploady": "^1.8.0",
"@rpldy/upload-button": "^1.8.0",
"@rpldy/upload-drop-zone": "^1.8.0",
"@rpldy/upload-preview": "^1.8.0",
"@rpldy/uploady": "^1.8.0",

**Comment by yoavniran** [comment]
hi @mariusschroeterCP 
I will look into this and let you know

**Comment by yoavniran** [comment]
fix (finally) released - https://github.com/rpldy/react-uploady/releases/tag/v1.8.1
