### ISSUE TITLE
TypeError: proxy[key] is null

### ISSUE THREAD

**Issue by efriandika** [rpldy/react-uploady#69]
Hi.. This library is really great.. I like this concept..
But, when I tries to implement it in my next.js app (just copy and paste from your example):

```
           <Uploady
                debug
                destination={{ url }}
            >
                <UploadButton>Upload Files</UploadButton>
            </Uploady>
```

I got this error: 
```
TypeError: proxy[key] is null
```

Any idea about this error?

**Comment by efriandika** [comment]
[UPDATE]

When I use previous version: v0.3.2, it works perfectly
Apparently, there is a problem with v0.4.0

**Comment by yoavniran** [comment]
thanks @efriandika
please share a reproducing repo/sandbox so i can see the error in runtime.

**Comment by efriandika** [comment]
Hi.. thanks for quick reply,

I will create a sample project for this, and letting you know then

**Comment by yoavniran** [comment]
hey @efriandika 
please check if 0.4.1 fixes your problem. #71 fixes a similar issue to the one your reported

**Comment by efriandika** [comment]
It works now... :D great...
I hace tested it...

Thank you very much
