### ISSUE TITLE
Improve UploadyProps to allow undefined values

### ISSUE THREAD

**Issue by meshuamam** [rpldy/react-uploady#710]
> Recommended - Check out the [discussions area](https://github.com/rpldy/react-uploady/discussions) before opening a new issue.

**Is your feature request related to a problem? Please describe.**
When passing UploadyProps, the current types only allow either for a value to not exist (marked by ?), or for it to have a value which isn't undefined.
```
export interface UploadyProps extends NoDomUploadyProps {
    customInput?: boolean;
    inputFieldContainer?: HTMLElement;
    capture?: string;
    multiple?: boolean;
    accept?: string;
    webkitdirectory?: boolean;
    fileInputId?: string;
    noPortal?: boolean;
}
```

this means, that code that wraps Uploady with custom props, can't be written like this:
```
export function UploadArea<T extends UploadType>(props: {  accept?: string }) {
return (
<Uploady
      destination={{ url: 'https://example.com }}
      accept={props.accept}
...
```
because Typescript will complain with `TS2375` that `Type undefined is not assignable to type string`

Instead, we must resort to this:
```
export function UploadArea<T extends UploadType>(props: {  accept?: string }) {
return (
<Uploady
      destination={{ url: 'https://example.com }}
      {...(props.accept && { accept: props.accept})}
...
```

**Describe the solution you'd like**
Change the UploadyProps to:
```
export interface UploadyProps extends NoDomUploadyProps {
    customInput?: boolean | undefined;
    inputFieldContainer?: HTMLElement | undefined;
    capture?: string | undefined;
    multiple?: boolean | undefined;
    accept?: string | undefined;
    webkitdirectory?: boolean | undefined;
    fileInputId?: string | undefined;
    noPortal?: boolean | undefined;
}
```

**Comment by yoavniran** [comment]
thanks @meshuamam !
Sounds good. I will try to get to it soon, or if you like, open a PR.

**Comment by yoavniran** [comment]
@meshuamam [version 1.8.2](https://github.com/rpldy/react-uploady/releases/tag/v1.8.2) released with the suggested improvement. 
Please let me know if there are any issues.
