### ISSUE TITLE
global Ctrl + v to paste images

### ISSUE THREAD

**Issue by denvey** [rpldy/react-uploady#749]
**Is your feature request related to a problem? Please describe.**  
Currently, there's no way to handle global `Ctrl + v` to paste images directly into the upload area. This feature would simplify workflows where users want to quickly upload images copied from other sources.

**Describe the solution you'd like**  
Support a global event listener for `Ctrl + v` that triggers the image upload process when an image is detected in the clipboard. This should work even if the upload area is not focused, providing a seamless user experience.

**Describe alternatives you've considered**  
An alternative would be to implement a custom solution using `window.addEventListener` for `paste` events, but it would be more efficient and consistent if this feature were supported natively in the library.
![image](https://github.com/user-attachments/assets/eb97a16f-17e5-45db-8744-4db911642720)
![image](https://github.com/user-attachments/assets/0ca7b489-9937-41d9-92fe-33a953c3c0a2)

**Additional context**  
Adding this feature would make the library more user-friendly for scenarios involving frequent image uploads, such as in chat applications or content management systems.

**Comment by yoavniran** [comment]
hey @denvey 
if you look at line 4 (in the first image you added), in case element isnt provided, the window becomes the target.

so doing this:

```js
 usePasteUpload(null, null, onPasteUpload);
```

would make the Window/Global become the paste target. 
Wouldn't that provide the capability you're looking for?

**Comment by denvey** [comment]
![image](https://github.com/user-attachments/assets/b25c856a-4a1b-47f5-880e-0ec3e3344065)

Thank you for your response. usePasteHandler can achieve this, but it will throw a type error. It would be even better if it could be optimized a bit.

**Comment by yoavniran** [comment]
thanks! I will fix the typing
