### ISSUE TITLE
useRequestPreSend isn't isolated

### ISSUE THREAD

**Issue by maxsalven** [rpldy/react-uploady#758]
Version 1.8.3

```javascript
import UploadButton from "@rpldy/upload-button";
import Uploady from "@rpldy/uploady";
import { useRequestPreSend } from "@rpldy/uploady";

const Hook = () => {
  useRequestPreSend((batch) => {
    if (batch.items[0]?.file.name === "a.txt") {
      return {
        options: {
          destination: {
            url: "/a",
            headers: { a: "true" },
          },
        },
      };
    } else if (batch.items[0]?.file.name === "b.txt") {
      return {
        options: {
          destination: {
            url: "/b",
            headers: { b: "true" },
          },
        },
      };
    } else {
      return false;
    }
  });
  return null;
};

const Uploader = () => {
  return (
    <Uploady multiple>
      <Hook />
      <UploadButton />
    </Uploady>
  );
};

export default Uploader;
```

If you upload multiple files at once, named `a.txt` and `b.txt`, then in the network call to `/b` you'll see it has both `a` and `b` headers:
<img width="522" alt="image" src="https://github.com/user-attachments/assets/34915b86-bc60-4528-8880-263061e4fcae">

I'd expect two separate file uploads to have isolated options, and not have them polluting each other.

This is a real world problem, as I need to send video uploads via tus, and all other uploads via xhr to different endpoints with different parameters (specifically, I need to override `send` with the regular xhr sender for non video files), but the requests end up overwriting each other and it ends up trying to use the xhr sender for the tus endpoint.

**Comment by yoavniran** [comment]
hey @maxsalven 
was on vacation this last couple of weeks.
will look into the issues in the next few days

**Comment by yoavniran** [comment]
This is actually a serious bug. Interesting how its never been raised before. 

The issue isn't with the isolation of the `useRequestPreSend` calls but indeed with the `destination` object being polluted across batches.  

Will fix soon. thanks!

**Comment by maxsalven** [comment]
Fantastic, thanks @yoavniran! Do you know if there's an easy way for me to test this in my app prior to an npm release being published?

**Comment by yoavniran** [comment]
I'll publish an RC version to npm for you to test with. 
Since next version will take a little longer with more fixes, the RC will let you test it once I publish (hopefully later today)

**Comment by yoavniran** [comment]
@maxsalven [RC version](https://github.com/rpldy/react-uploady/releases/tag/v1.9.0-rc.0) released and can be tested. 
Let me know if there's still an issue

**Comment by maxsalven** [comment]
@yoavniran I've been running this in production for the last 24 hours and everything seems to be working!

Thanks so much for your efforts.

**Comment by yoavniran** [comment]
great to hear. thanks for the update
