### ISSUE TITLE
sendDataOnCreate throws an error if file is smaller than chunkSize

### ISSUE THREAD

**Issue by maxsalven** [rpldy/react-uploady#759]
Version 1.8.3, Google Chrome

If I use `TusUploady` with `sendDataOnCreate`, if the file I'm uploading is smaller than the `chunkSize` prop, then I get an error in the console and the batch never finishes.

`@rpldy_tus-uploady.js?v=84958b3e:122 Uncaught (in promise) ChunkedSendError: start byte 16294884 is invalid. File size: 16294884`
<img width="706" alt="Screenshot 2024-10-13 at 18 02 01" src="https://github.com/user-attachments/assets/2a4b0c83-68ac-42ab-8fbb-530dbf171560">

It works fine with `sendDataOnCreate` disabled, or if the file is bigger than the chunk size.

Note the upload actually does complete successfully, but Uploady doesn't reflect that.

**Comment by yoavniran** [comment]
thanks for reporting @maxsalven 
definitely sounds like a bug. Will try and fix soon

**Comment by yoavniran** [comment]
@maxsalven just published [1.9.0-rc.1](https://github.com/rpldy/react-uploady/releases/tag/v1.9.0-rc.1) with a fix for this issue.
If you can test it and let me know that it works, it'll be great.
