### ISSUE TITLE
Window is not defined - ssr problem

### ISSUE THREAD

**Issue by omcg33** [rpldy/react-uploady#76]
Trying to use your great package with SSR.
But I got error on server 
```
ReferenceError: window is not defined
    at Object.<anonymous> (/*/node_modules/@rpldy/uploader/lib/utils.js:16:40)
```

My config
"@rpldy/upload-drop-zone": "^0.5.0",
"@rpldy/uploady": "^0.5.0",

```
<Uploady
              multiple
              grouped
              maxGroupSize={2}
              method="POST"
              destination={{url: generateApiUrl(API_ROUTES_POST.FILES, {method: "POST"}) }}
            >
              <UploadDropZone
                onDragOverClassName="drag-over"
                grouped={grouped}
                maxGroupSize={groupSize}
              >
                <span>Drag&Drop File(s) Here</span>
              </UploadDropZone>
</Uploady>
```

**Comment by yoavniran** [comment]
thanks @omcg33 
is there a repo or codesandbox i can reproduce the issue with? It will save a lot of time

**Comment by omcg33** [comment]
Sorry. But sandboxes does not has functionality for SSR.

I think solution is - Dont read from window without check typeof window !== "undefined".

I change 
/*/node_modules/@rpldy/uploader/lib/utils.js:16:40
to 
```
var FILE_LIST_SUPPORT = (typeof window !== "undefined" && "FileList" in window);
```

And my server normaly render Your Component

**Comment by omcg33** [comment]
Can i help you for faster fix?

**Comment by yoavniran** [comment]
thanks @omcg33 
fixing the window only revealed additional issues. I expect to have a fix in the coming day or two

**Comment by yoavniran** [comment]
@omcg33 please check with 0.6.0. SSR support is now released

**Comment by omcg33** [comment]
Ssr works in 0.6.0 
Thanks

**Comment by jordie23** [comment]
I think there's still an issue here: https://github.com/rpldy/react-uploady/blob/7a60edb7e81085dded8a6d78888060945a1e1066/packages/core/simple-state/src/utils.js#L10

I'm getting `ReferenceError: File is not defined` on the server side

**Comment by yoavniran** [comment]
@jordie23 that would make sense since File isnt available in Node.

However, I dont understand how you are getting to this point in the code on the server side. This flow is only expected to run on the client (since it means an upload has begun). 

Please open a new issue and add more details about how you are using Uploady and any other detail about this error (stacktrace) 

A reproducing sandbox/repo will be very useful of course too
