### ISSUE TITLE
tus-uploady: Location not available in uploadResponse on UPLOADER_EVENTS.ITEM_FINISH

### ISSUE THREAD

**Issue by RubenGarcia** [rpldy/react-uploady#86]
**Describe the bug**
When uploading a file using tus-uploady, the Location is provided by the tus server.
However, on UPLOADER_EVENTS.ITEM_FINISH I seem to be getting the response of the last PATCH:
	data: ""
	headers:
	cache-control: "no-store"
	content-length: "0"
	content-type: "text/html; charset=utf-8"
	tus-res	umable: "1.0.0"
	upload-offset: "469"
instead of the response of the last POST with the Location information

**To Reproduce**
Upload a file using the library, and search for the Location header in uploadResponse

**Expected behavior**
Location header is available

**Versions**
Specify the versions of the @rpldy packages you're using: 0.6.0
Which browser this bug reproduces in: Chrome 85

**Code**
const tusEnhancer = getTusEnhancer({
	            parallel: 1,   
	        });
	const random = "asdfqwfwefiqwfpjoqwef"
	const uploader = createUploader({ 
		enhancer: tusEnhancer,
			autoUpload: true,
			grouped: false,
		destination: {url: "https://<host>/upload/",
		              filesParamName: random,
			      headers: {Authorization: getAuthorization()}
		},
		params: {
			project: "p",
			access: "a",
		},
		sendDataOnCreate: true,
	});
	uploader.add (file);

**Comment by yoavniran** [comment]
thanks @RubenGarcia for the detailed info.
fix will be available soon as part of 0.6.1

the location info will be accessible as a new property of the item's `uploadResponse`

for example, through the item finish hook, you'll be able to access it:

```javascript
 
  useItemFinishListener((item) => {
          console.log(item.uploadResponse.location);
        });
```

or through an event handler:

```javascript
uploader.on(UPLOADER_EVENTS.ITEM_FINISH, (item) => {
          console.log(item.uploadResponse.location);
    });
```

**Comment by yoavniran** [comment]
@RubenGarcia 0.7.0 is now out. Please check and let me know if there are any issues

**Comment by RubenGarcia** [comment]
I confirm I can access the location.
