### ISSUE TITLE
The `accept` parameter is ignored when dragging and dropping files. 

### ISSUE THREAD

**Issue by claireryberg** [rpldy/react-uploady#92]
**Describe the bug**
The `accept` parameter is ignored when dragging and dropping files. For example, when set to `accept="image/*"`, non-image file types cannot get uploaded from the `UploadButton` but they _are_ uploaded when dragging and dropping.

**To Reproduce**
1. If you click the `UploadButton` in the provided codesandbox and the native file browser will appear. For me, using Chrome 85 on Mac Mojave, all non-image file types appear greyed out and cannot be selected.
2. Open the Network tab in the dev tools
3. Drag a non-image file into the `UploadDropZone` (I used a .mov type)
4. A network request is triggered to upload the file

**Expected behavior**
Only file types that are listed in the `accept` parameter can be uploaded. In this case, a non-image would not trigger a network request, and there would be some kind of error response from Uploady.

**Versions**
"@rpldy/upload-button": "0.7.0",
"@rpldy/upload-drop-zone": "0.7.0",
"@rpldy/uploady": "0.7.0"

**Code**
https://codesandbox.io/s/uploady-example-55600

**Comment by yoavniran** [comment]
the _accept_ parameter is indeed only for the file input.
I suggest using the _[fileFilter](https://github.com/rpldy/react-uploady/blob/master/guides/FileFilter.md)_ function to ensure you only upload the desired files, regardless of how they are provided

**Comment by claireryberg** [comment]
I see, it wasn't clear to me that `accept` is scoped only to the file browser. Thanks!
